# Generated by Django 2.2.4 on 2019-12-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
