# Generated by Django 2.2.4 on 2019-12-21 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
